version: '3'

services:

  tomcat:
    build: ./cvs_tomcat
    container_name: pharmacylocator-tomcat
    ports:
      - "8443:8080"

  fs_tomcat:
    build: ./fs_tomcat
    container_name: pharmacylocator-fs-tomcat
    ports:
      - "8553:8080"

  mariadb:
    image: mariadb:latest
    container_name: pharmacylocator-mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=password
    restart: always
    volumes:
      - /home/volumes/mariadb-data:/var/lib/mysql
    ports:
      - "3306:3306"

  jenkins:
    image: jenkins/jenkins:lts
    container_name: pharmacylocator-jenkins
    environment:
      - JENKINS_OPTS="--httpPort=8087"
    restart: always
    volumes:
      - /home/volumes/jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /root:/home
    ports:
      - "8888:8087"

  postgres:
    container_name: postgres
    image: postgres:10.1
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - /home/volumes/postgres-data:/var/lib/postgresql
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
      - POSTGRES_DB=sonarqube

  sonarqube:
    image: sonarqube:6.7.3
    restart: always
    container_name: pharmacylocator-sonarqube
    links:
      - postgres
    ports:
      - "9000:9000"
      - "9092:9092"
    environment:
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar
      - SONARQUBE_JDBC_URL=jdbc:postgresql://192.168.1.154:5432/sonarqube
    volumes:
      - /home/volumes/sonarqube-data/sonarqube_conf:/opt/sonarqube/conf
      - /home/volumes/sonarqube-data/sonarqube_data:/opt/sonarqube/data
      - /home/volumes/sonarqube-data/sonarqube_extensions:/opt/sonarqube/extensions
      - /home/volumes/sonarqube-data/sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins

  clamav-app:
    image: mkodockx/docker-clamav
    container_name: clamav-app
    volumes:
      - /home/volumes/clamav-data:/data
      - /home/volumes/clamav-data/logs:/var/log/clamav
    environment:
      - ZABBIX_HOSTNAME=clamav-app
    restart: always
    ports:
      - "3310:3310"
